# Basic
title: 叫兽自留地
description: 一个寻道路上的非优秀程序猿~

url: "https://github.com/youran1024"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 随想
    description: 可能是个奇葩的人

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/youran1024'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: youran1024
    github: youran1024
    twitter: youran1024
    mail: youran1024@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
